[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aave/core-v3=lib/aave-v3-core/",
    "@chainlink/contracts=lib/chainlink-brownie-contracts/contracts/",
    "forge-std/=lib/forge-std/src/",
    "solmate/=lib/solmate/src/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
